# File name: screenmanager.kv
#:import FadeTransition kivy.uix.screenmanager.FadeTransition
#:import SwapTransition kivy.uix.screenmanager.SwapTransition
#:import SlideTransition kivy.uix.screenmanager.SlideTransition
#:import WipeTransition kivy.uix.screenmanager.WipeTransition
#:import NoTransition kivy.uix.screenmanager.NoTransition
<ScreenManager>:
    #transition: FadeTransition()
    transition: NoTransition()
